name: GeorgianMemenator
options:
  bundleIdPrefix: io.applysis
  deploymentTarget:
    iOS: 14.0
targets:
  GeorgianMemenator:
    type: application
    platform: iOS
    sources: 
      - path: GeorgianMemenator
    scheme:
      testTargets:
      - GeorgianMemenatorTests
  GeorgianMemenatorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GeorgianMemenatorTests